import * as fs from 'node:fs';
import * as path from 'node:path';
import type { CmsContentMap } from './types.js';

export function writeContentArtifacts(outputDir: string, content: CmsContentMap): void {
	fs.mkdirSync(outputDir, { recursive: true });
	fs.writeFileSync(path.join(outputDir, 'cms-content.json'), JSON.stringify(content, null, 2), 'utf-8');
	fs.writeFileSync(path.join(outputDir, 'cms-content-data.ts'), generateContentData(), 'utf-8');
}

function generateContentData(): string {
	return `// Auto-generated by @patstore/cms-content-plugin — do not edit
import content from './cms-content.json';

export interface CmsContentEntry {
	path: string;
	value: unknown;
}

/** Page path → \`page_data\` entries. Locale is a prefix on \`path\` (\`de-DE.home_start.title\`). */
export interface CmsContentPages {
	[path: string]: CmsContentEntry[];
}

interface CmsContentFile {
	_meta: { generatedAt: string; projectId: string; source: 'cms' | 'defaults'; languages: string[] };
	pages: CmsContentPages;
}

const data = content as CmsContentFile;

export function isCmsContentReady(): boolean {
	return Boolean(data._meta?.generatedAt);
}

/** \`de\` → \`de-DE\`. \`default\` stays \`default\`. */
function toLocale(value: string): string {
	const trimmed = value.trim();
	if (!trimmed || trimmed.toLowerCase() === 'default') {
		return 'default';
	}
	const parts = trimmed.split(/[-_]/).filter(Boolean);
	const language = parts[0]?.toLowerCase();
	if (!language) {
		return 'default';
	}
	const region = (parts[1] ?? parts[0]).toUpperCase();
	return \`\${language}-\${region}\`;
}

const LOCALE_PATH = /^[a-z]{2}-[A-Z]{2}\\./;

/**
 * Resolves \`pagePath\`'s \`page_data\` entries for \`locale\`.
 * Entries are \`{ path, value }\` as stored. \`home_start.title\` is the default;
 * \`de-DE.home_start.title\` overrides it for that locale. With no languages or
 * only one, only unprefixed paths are returned.
 */
export function getPageContent(pagePath: string, locale: string): Record<string, unknown> {
	const entries = data.pages[pagePath];
	if (!Array.isArray(entries)) {
		return {};
	}
	const resolved: Record<string, unknown> = {};
	for (const entry of entries) {
		if (!entry || typeof entry.path !== 'string' || LOCALE_PATH.test(entry.path)) {
			continue;
		}
		resolved[entry.path] = entry.value;
	}
	const languages = data._meta?.languages ?? [];
	if (languages.length <= 1) {
		return resolved;
	}
	const prefix = \`\${toLocale(locale)}.\`;
	for (const entry of entries) {
		if (!entry || typeof entry.path !== 'string' || !entry.path.startsWith(prefix)) {
			continue;
		}
		resolved[entry.path.slice(prefix.length)] = entry.value;
	}
	return resolved;
}

export function getAllPageContent(): CmsContentPages {
	return data.pages;
}
`;
}

export function writeStubContentArtifacts(outputDir: string): void {
	writeContentArtifacts(outputDir, {
		_meta: { generatedAt: '', projectId: '', source: 'defaults', languages: [] },
		pages: {},
	});
}
