import * as fs from 'node:fs';
import * as path from 'node:path';
import type { CmsContentMap } from './types.js';

export function writeContentArtifacts(outputDir: string, content: CmsContentMap): void {
	fs.mkdirSync(outputDir, { recursive: true });
	fs.writeFileSync(path.join(outputDir, 'cms-content.json'), JSON.stringify(content, null, 2), 'utf-8');
	fs.writeFileSync(path.join(outputDir, 'cms-content-data.ts'), generateContentData(), 'utf-8');
}

function generateContentData(): string {
	return `// Auto-generated by @patstore/cms-content-plugin — do not edit
import content from './cms-content.json';

export interface CmsContentPages {
	[path: string]: Record<string, Record<string, unknown>>;
}

interface CmsContentFile {
	_meta: { generatedAt: string; projectId: string; source: 'cms' | 'defaults'; languages: string[] };
	pages: CmsContentPages;
}

const data = content as CmsContentFile;

export function isCmsContentReady(): boolean {
	return Boolean(data._meta?.generatedAt);
}

/** Resolves \`pagePath\`'s content for \`lang\` — falls back to whichever language synced first when \`lang\` has no entry. */
export function getPageContent(pagePath: string, lang: string): Record<string, unknown> {
	const page = data.pages[pagePath];
	if (!page) {
		return {};
	}
	if (page[lang]) {
		return page[lang];
	}
	const fallbackLang = Object.keys(page)[0];
	return fallbackLang ? page[fallbackLang] : {};
}

export function getAllPageContent(): CmsContentPages {
	return data.pages;
}
`;
}

export function writeStubContentArtifacts(outputDir: string): void {
	writeContentArtifacts(outputDir, {
		_meta: { generatedAt: '', projectId: '', source: 'defaults', languages: [] },
		pages: {},
	});
}
