import * as fs from 'node:fs';
import * as path from 'node:path';
import type { CmsContentMap } from './types.js';

export function writeContentArtifacts(outputDir: string, content: CmsContentMap): void {
	fs.mkdirSync(outputDir, { recursive: true });
	fs.writeFileSync(path.join(outputDir, 'cms-content.json'), JSON.stringify(content, null, 2), 'utf-8');
	fs.writeFileSync(path.join(outputDir, 'cms-content-data.ts'), generateContentData(), 'utf-8');
}

function generateContentData(): string {
	return `// Auto-generated by @patstore/cms-content-plugin — do not edit
import content from './cms-content.json';

export interface CmsContentPages {
	[path: string]: Record<string, Record<string, unknown>>;
}

interface CmsContentFile {
	_meta: { generatedAt: string; projectId: string; source: 'cms' | 'defaults'; languages: string[] };
	pages: CmsContentPages;
}

const data = content as CmsContentFile;

export function isCmsContentReady(): boolean {
	return Boolean(data._meta?.generatedAt);
}

/** \`de\` → \`de-DE\`. \`default\` stays \`default\`. */
function toLocale(value: string): string {
	const trimmed = value.trim();
	if (!trimmed || trimmed.toLowerCase() === 'default') {
		return 'default';
	}
	const parts = trimmed.split(/[-_]/).filter(Boolean);
	const language = parts[0]?.toLowerCase();
	if (!language) {
		return 'default';
	}
	const region = (parts[1] ?? parts[0]).toUpperCase();
	return \`\${language}-\${region}\`;
}

/**
 * Resolves \`pagePath\`'s \`page_content\` for \`locale\` (\`de-DE\`).
 * Uses \`default\` when the project has no languages or only one.
 */
export function getPageContent(pagePath: string, locale: string): Record<string, unknown> {
	const page = data.pages[pagePath];
	if (!page) {
		return {};
	}
	const languages = data._meta?.languages ?? [];
	if (languages.length <= 1) {
		return page.default ?? {};
	}
	const normalized = toLocale(locale);
	if (page[normalized]) {
		return page[normalized];
	}
	if (page.default) {
		return page.default;
	}
	const fallback = Object.keys(page)[0];
	return fallback ? page[fallback] : {};
}

export function getAllPageContent(): CmsContentPages {
	return data.pages;
}
`;
}

export function writeStubContentArtifacts(outputDir: string): void {
	writeContentArtifacts(outputDir, {
		_meta: { generatedAt: '', projectId: '', source: 'defaults', languages: [] },
		pages: {},
	});
}
