import * as fs from 'node:fs';
import * as path from 'node:path';
import {
	generatePatstoreTypesSource,
	listPatstoreTypeEntries,
	type PatstoreTypeEntry,
} from '@patstore/core';
import type { BuildTimeData } from './ssg-fetcher.js';

export function writeBuildTimeArtifacts(outputDir: string, data: BuildTimeData): void {
	fs.mkdirSync(outputDir, { recursive: true });

	const serializable = { ...data };
	fs.writeFileSync(
		path.join(outputDir, 'build-time-data.json'),
		JSON.stringify(serializable, null, 2),
		'utf-8',
	);

	const collectionKeys = Object.keys(data).filter(
		(key) => !key.startsWith('_') && key !== 'downloadedFiles' && Array.isArray(data[key]),
	);
	const modules = Array.isArray(data._modules) ? data._modules : [];
	const entries = listPatstoreTypeEntries(modules);

	const legacyTypesFile = path.join(outputDir, 'types.ts');
	if (fs.existsSync(legacyTypesFile) && fs.statSync(legacyTypesFile).isFile()) {
		fs.unlinkSync(legacyTypesFile);
	}

	const typesDir = path.join(outputDir, 'types');
	fs.mkdirSync(typesDir, { recursive: true });
	fs.writeFileSync(path.join(typesDir, 'index.ts'), generatePatstoreTypesSource(modules), 'utf-8');

	fs.writeFileSync(
		path.join(outputDir, 'build-time-types.ts'),
		generateBuildTimeTypes(entries, collectionKeys),
		'utf-8',
	);
	fs.writeFileSync(path.join(outputDir, 'access.ts'), generateAccess(entries), 'utf-8');
	fs.writeFileSync(path.join(outputDir, 'index.ts'), generateIndex(entries), 'utf-8');
	writeAmbientCmsModule(outputDir);
}

function generateBuildTimeTypes(entries: PatstoreTypeEntry[], collectionKeys: string[]): string {
	const typedKeys = new Set(entries.map((entry) => entry.storageKey));
	const extraKeys = collectionKeys.filter((key) => !typedKeys.has(key));
	const typeNames = entries.map((entry) => entry.typeName);
	const importLine =
		typeNames.length > 0
			? `import type { ${typeNames.join(', ')} } from './types/index.ts';\n\n`
			: '';

	const collectionProps = [
		...entries.map((entry) => `  ${entry.storageKey}?: ${entry.typeName}[];`),
		...extraKeys.map((key) => `  ${key}?: Record<string, unknown>[];`),
	].join('\n');

	return `// Auto-generated by vite-plugin-patstore — do not edit
${importLine}export interface BuildTimeMeta {
  generatedAt: string;
  projectId: string;
  moduleCount: number;
}

export interface DownloadedFile {
  objectId: string;
  originalUrl: string;
  localPath: string;
  filename: string;
  type: 'image' | 'document';
}

export interface BuildTimeData {
  _meta: BuildTimeMeta;
  _modules: unknown[];
  downloadedFiles?: DownloadedFile[];
${collectionProps}
  [key: string]: unknown;
}
`;
}

function generateAccess(entries: PatstoreTypeEntry[]): string {
	const typeNames = entries.map((entry) => entry.typeName);
	const typeImport =
		typeNames.length > 0
			? `import type { ${typeNames.join(', ')} } from './types/index.ts';\n`
			: '';

	const findByOverloads = entries
		.map(
			({ className, typeName }) =>
				`export function findByClassName(className: '${className}'): ${typeName}[];`,
		)
		.join('\n');

	const findStaticOverloads = entries
		.map(
			({ className, typeName }) =>
				`export function findStaticCollection(className: '${className}', limit?: number): ${typeName}[];`,
		)
		.join('\n');

	const mapEntries = entries
		.map(({ storageKey, className }) => `  ${className}: '${storageKey}',`)
		.join('\n');

	return `// Auto-generated by vite-plugin-patstore — do not edit
import buildTimeData from './build-time-data.json';
import type { BuildTimeData } from './build-time-types.ts';
${typeImport}
const data = buildTimeData as BuildTimeData;

const CLASS_TO_KEY: Record<string, string> = {
${mapEntries}
};

export function isStaticDataReady(): boolean {
  return Boolean(data._meta?.generatedAt);
}

export function getBuildTimeData(): BuildTimeData {
  return data;
}

${findByOverloads}
export function findByClassName(className: string): Record<string, unknown>[] {
  const mapped = CLASS_TO_KEY[className];
  const key = mapped ?? className;
  const bucket = data[key];
  return Array.isArray(bucket) ? bucket : [];
}

export function findByObjectId(objectId: string): Record<string, unknown> | null {
  for (const [key, value] of Object.entries(data)) {
    if (!Array.isArray(value) || key.startsWith('_')) continue;
    const found = value.find((item) => item.objectId === objectId);
    if (found) return found as Record<string, unknown>;
  }
  return null;
}

${findStaticOverloads}
export function findStaticCollection<T extends { objectId: string }>(
  className: string,
  limit?: number,
): T[] {
  const mapped = CLASS_TO_KEY[className];
  const key = mapped ?? className;
  const bucket = data[key];
  const items = (Array.isArray(bucket) ? bucket : []) as T[];
  return limit ? items.slice(0, limit) : items;
}
`;
}

function generateIndex(entries: PatstoreTypeEntry[]): string {
	const typeExports =
		entries.length > 0
			? `export type { ${entries.map((entry) => entry.typeName).join(', ')}, PatstoreRecord } from './types/index.ts';\n`
			: `export type { PatstoreRecord } from './types/index.ts';\n`;

	return `// Auto-generated by vite-plugin-patstore — do not edit
export {
  findByClassName,
  findByObjectId,
  findStaticCollection,
  getBuildTimeData,
  isStaticDataReady,
} from './access.ts';
export type { BuildTimeData, BuildTimeMeta, DownloadedFile } from './build-time-types.ts';
${typeExports}export { default as buildTimeData } from './build-time-data.json';
`;
}

function posixRelative(from: string, to: string): string {
	let relative = path.relative(from, to).replace(/\\/g, '/');
	if (!relative.startsWith('.')) {
		relative = `./${relative}`;
	}
	return relative;
}

/** Ambient `declare module '@cms'` / `@data` so tsc resolves the aliases without tsconfig paths. */
function writeAmbientCmsModule(outputDir: string): void {
	const root = process.cwd();
	const srcDir = path.join(root, 'src');
	const destDir = fs.existsSync(srcDir) ? srcDir : root;
	const typesIndex = path.join(outputDir, 'types', 'index.ts');
	const dataIndex = path.join(outputDir, 'index.ts');

	const destFile = path.join(destDir, 'patstore-cms.d.ts');
	if (fs.existsSync(destFile)) {
		const existing = fs.readFileSync(destFile, 'utf-8');
		if (!existing.startsWith('// Auto-generated by vite-plugin-patstore')) {
			return;
		}
	}

	fs.writeFileSync(
		destFile,
		`// Auto-generated by vite-plugin-patstore — do not edit
declare module '@cms' {
  export * from '${posixRelative(destDir, typesIndex)}';
}
declare module '@data' {
  export * from '${posixRelative(destDir, dataIndex)}';
}
`,
		'utf-8',
	);
}

export function writeStubArtifacts(outputDir: string): void {
	writeBuildTimeArtifacts(outputDir, {
		_meta: {
			generatedAt: '',
			projectId: '',
			moduleCount: 0,
		},
		_modules: [],
	});
}
