import * as fs from 'node:fs';
import * as path from 'node:path';
import type { BuildTimeData } from './ssg-fetcher.js';
import { getStorageKey } from '@patstore/core';

export function writeBuildTimeArtifacts(outputDir: string, data: BuildTimeData): void {
	fs.mkdirSync(outputDir, { recursive: true });

	const serializable = { ...data };
	fs.writeFileSync(
		path.join(outputDir, 'build-time-data.json'),
		JSON.stringify(serializable, null, 2),
		'utf-8',
	);

	const collectionKeys = Object.keys(data).filter(
		(key) => !key.startsWith('_') && key !== 'downloadedFiles' && Array.isArray(data[key]),
	);

	fs.writeFileSync(path.join(outputDir, 'types.ts'), generateTypes(collectionKeys), 'utf-8');
	fs.writeFileSync(path.join(outputDir, 'access.ts'), generateAccess(collectionKeys), 'utf-8');
	fs.writeFileSync(path.join(outputDir, 'index.ts'), generateIndex(), 'utf-8');
}

function generateTypes(collectionKeys: string[]): string {
	return `// Auto-generated by vite-plugin-patstore — do not edit

export interface BuildTimeMeta {
  generatedAt: string;
  projectId: string;
  moduleCount: number;
}

export interface DownloadedFile {
  objectId: string;
  originalUrl: string;
  localPath: string;
  filename: string;
  type: 'image' | 'document';
}

export interface BuildTimeData {
  _meta: BuildTimeMeta;
  _modules: unknown[];
  downloadedFiles?: DownloadedFile[];
${collectionKeys.map((key) => `  ${key}?: Record<string, unknown>[];`).join('\n')}
  [key: string]: unknown;
}
`;
}

function generateAccess(collectionKeys: string[]): string {
	const classEntries = collectionKeys
		.map((key) => {
			const singular = key.endsWith('ies')
				? key.slice(0, -3) + 'y'
				: key.endsWith('s')
					? key.slice(0, -1)
					: key;
			const className = singular.charAt(0).toUpperCase() + singular.slice(1);
			return { key, className };
		});

	const overloads = classEntries
		.map(({ className }) => `export function findByClassName(className: '${className}'): Record<string, unknown>[];`)
		.join('\n');

	const mapEntries = classEntries
		.map(({ key, className }) => `  ${className}: '${key}',`)
		.join('\n');

	return `// Auto-generated by vite-plugin-patstore — do not edit
import buildTimeData from './build-time-data.json';
import type { BuildTimeData } from './types.ts';

const data = buildTimeData as BuildTimeData;

const CLASS_TO_KEY: Record<string, string> = {
${mapEntries}
};

export function isStaticDataReady(): boolean {
  return Boolean(data._meta?.generatedAt);
}

export function getBuildTimeData(): BuildTimeData {
  return data;
}

${overloads}
export function findByClassName(className: string): Record<string, unknown>[] {
  const mapped = CLASS_TO_KEY[className];
  const key = mapped ?? className;
  const bucket = data[key];
  return Array.isArray(bucket) ? bucket : [];
}

export function findByObjectId(objectId: string): Record<string, unknown> | null {
  for (const [key, value] of Object.entries(data)) {
    if (!Array.isArray(value) || key.startsWith('_')) continue;
    const found = value.find((item) => item.objectId === objectId);
    if (found) return found as Record<string, unknown>;
  }
  return null;
}

export function findStaticCollection<T extends { objectId: string }>(
  className: string,
  limit?: number,
): T[] {
  const mapped = CLASS_TO_KEY[className];
  const key = mapped ?? className;
  const bucket = data[key];
  const items = (Array.isArray(bucket) ? bucket : []) as T[];
  return limit ? items.slice(0, limit) : items;
}
`;
}

function generateIndex(): string {
	return `// Auto-generated by vite-plugin-patstore — do not edit
export {
  findByClassName,
  findByObjectId,
  findStaticCollection,
  getBuildTimeData,
  isStaticDataReady,
} from './access.ts';
export type { BuildTimeData, BuildTimeMeta, DownloadedFile } from './types.ts';
export { default as buildTimeData } from './build-time-data.json';
`;
}

export function writeStubArtifacts(outputDir: string): void {
	writeBuildTimeArtifacts(outputDir, {
		_meta: {
			generatedAt: '',
			projectId: '',
			moduleCount: 0,
		},
		_modules: [],
	});
}
