import * as fs from 'node:fs';
import * as path from 'node:path';
import { importAliasForRoute, scanPagesDir, type ScannedPageRoute } from './scan-pages.js';

export interface GenerateRoutesOptions {
	pagesDir: string;
	outputDir: string;
}

function renderRouteMatchBlock(routes: ScannedPageRoute[]): string {
	if (routes.length === 0) {
		return '\treturn null;\n';
	}

	const lines: string[] = ['\tconst normalized = normalizeRoutePath(pathname);', ''];

	for (const route of routes) {
		lines.push('\t{');
		lines.push(`\t\tconst params = matchRoutePattern('${route.pattern}', normalized);`);
		lines.push('\t\tif (params) {');
		lines.push(`\t\t\treturn { id: '${route.id}', pattern: '${route.pattern}', params };`);
		lines.push('\t\t}');
		lines.push('\t}');
		lines.push('');
	}

	lines.push('\treturn null;');
	return lines.join('\n');
}

function renderPageRouterBody(
	routes: ScannedPageRoute[],
	notFoundComponent: string,
	fileAliases: Map<string, string>,
): string {
	const lines: string[] = [
		'\tconst { path } = useRouter();',
		'\tconst match = matchRoute(path);',
		'\tconst language = resolveRouteLanguage(match?.params);',
		'',
	];

	if (routes.length === 0) {
		lines.push(`\t<${notFoundComponent} language={language} />`);
		return lines.join('\n');
	}

	lines.push('\t@if (!match) {');
	lines.push(`\t\t<${notFoundComponent} language={language} />`);

	for (const route of routes) {
		const alias = importAliasForRoute(route, fileAliases);
		lines.push(`\t} @else if (match.id === '${route.id}') {`);
		lines.push(`\t\t<${alias} language={language} />`);
	}

	lines.push('\t} @else {');
	lines.push(`\t\t<${notFoundComponent} language={language} />`);
	lines.push('\t}');

	return lines.join('\n');
}

function renderImportLines(scanned: ReturnType<typeof scanPagesDir>): string {
	const imports = new Map<string, { componentName: string; importPath: string }>();

	for (const route of scanned.routes) {
		const alias = importAliasForRoute(route, scanned.fileAliases);
		if (!imports.has(alias)) {
			imports.set(alias, {
				componentName: route.componentName,
				importPath: route.importPath,
			});
		}
	}

	if (scanned.notFound) {
		imports.set(scanned.notFound.importAlias, {
			componentName: scanned.notFound.componentName,
			importPath: scanned.notFound.importPath,
		});
	}

	return [...imports.entries()]
		.sort(([a], [b]) => a.localeCompare(b))
		.map(
			([alias, { componentName, importPath }]) =>
				`import { ${componentName} as ${alias} } from '${importPath}';`,
		)
		.join('\n');
}

export function generateRoutes(options: GenerateRoutesOptions): void {
	const { pagesDir, outputDir } = options;
	const scanned = scanPagesDir(pagesDir);

	fs.mkdirSync(outputDir, { recursive: true });

	const notFoundAlias = scanned.notFound?.importAlias ?? 'Page_404';

	const routesTs = `// Auto-generated by octane-pages-plugin — do not edit

export interface RouteMatch {
	id: string;
	/** Route pattern this match resolved against, e.g. /athletes/$slug. */
	pattern: string;
	params: Record<string, string>;
}

export function normalizeRoutePath(pathname: string): string {
	const path = pathname.split('?')[0]?.split('#')[0] ?? '/';
	if (path === '/' || path === '') {
		return '/';
	}
	return path.replace(/\\/+$/, '') || '/';
}

export function matchRoutePattern(pattern: string, pathname: string): Record<string, string> | null {
	const normalized = normalizeRoutePath(pathname);

	if (pattern === '/') {
		return normalized === '/' ? {} : null;
	}

	const patternParts = pattern.split('/').filter(Boolean);
	const pathParts = normalized.split('/').filter(Boolean);

	if (patternParts[patternParts.length - 1] === '$') {
		const prefix = patternParts.slice(0, -1);
		if (pathParts.length < prefix.length) {
			return null;
		}

		for (let i = 0; i < prefix.length; i++) {
			const patternPart = prefix[i]!;
			const pathPart = pathParts[i]!;
			if (patternPart.startsWith('$')) {
				continue;
			}
			if (patternPart !== pathPart) {
				return null;
			}
		}

		const params: Record<string, string> = {};
		for (let i = 0; i < prefix.length; i++) {
			const patternPart = prefix[i]!;
			const pathPart = pathParts[i]!;
			if (patternPart.startsWith('$')) {
				params[patternPart.slice(1)] = decodeURIComponent(pathPart);
			}
		}

		params._splat = pathParts.slice(prefix.length).map(decodeURIComponent).join('/');
		return params;
	}

	if (patternParts.length !== pathParts.length) {
		return null;
	}

	const params: Record<string, string> = {};
	for (let i = 0; i < patternParts.length; i++) {
		const patternPart = patternParts[i]!;
		const pathPart = pathParts[i]!;
		if (patternPart.startsWith('$')) {
			params[patternPart.slice(1)] = decodeURIComponent(pathPart);
		} else if (patternPart !== pathPart) {
			return null;
		}
	}

	return params;
}

export function matchRoute(pathname: string): RouteMatch | null {
${renderRouteMatchBlock(scanned.routes)}
}

function cmsPathForPattern(pattern: string): string | null {
	const segments = pattern.split('/').filter(Boolean);
	if (segments.at(-1) === '$') {
		return null;
	}
	const stripped = segments.filter((segment) => segment !== '$lang');
	return stripped.length === 0 ? '/' : \`/\${stripped.join('/')}\`;
}

export function cmsContentPath(pathname: string): string {
	const match = matchRoute(pathname);
	if (!match) {
		return normalizeRoutePath(pathname);
	}
	return cmsPathForPattern(match.pattern) ?? normalizeRoutePath(pathname);
}
`;

	const importLines = renderImportLines(scanned);

	const pageRouterTsx = `// Auto-generated by octane-pages-plugin — do not edit
import { resolveRouteLanguage, useRouter } from '@provider';
${importLines}
import { matchRoute } from './routes.ts';

export function PageRouter() @{
${renderPageRouterBody(scanned.routes, notFoundAlias, scanned.fileAliases)}
}
`;

	fs.writeFileSync(path.join(outputDir, 'routes.ts'), routesTs, 'utf-8');
	fs.writeFileSync(path.join(outputDir, 'PageRouter.tsrx'), pageRouterTsx, 'utf-8');
}
